import json
from datetime import datetime
from typing import Optional

from mcp.server.fastmcp import FastMCP
from pydantic import Field

from config import config
from context import get_app_context
from logging_config import get_logger
from tools._base import call_backend
from utils import require_auth, save_report

logger = get_logger(__name__)


def register_pharmacy_report_tools(mcp: FastMCP):
    logger.info("Registering pharmacy report tool with MCP server")

    defaults = config.tool_defaults.pharmacy
    weights = defaults.scoring_weights

    def _build_markdown(city_name: str, html_file_path: str) -> str:
        date_str = datetime.now().strftime("%B %d, %Y")
        if "reports" in html_file_path:
            relative = html_file_path.split("reports", 1)[-1].replace("\\", "/").lstrip("/")
            web_url = f"{config.backend.url}/static/reports/{relative}"
        else:
            web_url = html_file_path
        return (
            f"# Pharmacy Site Analysis Report - {city_name}\n\n"
            f"Analysis completed for {city_name} on {date_str}.\n\n"
            f"[Click here to see full report]({web_url})\n\n"
            "---\nGenerated by Geospatial Intelligence Platform\n"
        )

    @mcp.tool(
        name="generate_pharmacy_report",
        description="""Generate comprehensive pharmacy site selection reports with real-time analysis.

        Analyzes locations based on multiple criteria including traffic, demographics, competition,
        healthcare ecosystem, and complementary businesses. Supports custom locations and evaluation metrics.

        Returns a detailed pharmacy site analysis report with rankings and investment recommendations.
        """,
    )
    async def generate_pharmacy_report(
        city_name: str = Field(default=defaults.city_name, description="Target city for pharmacy site analysis"),
        country_name: str = Field(default=defaults.country_name, description="Target country"),
        traffic_weight: float = Field(default=weights.traffic, description="Weight for traffic score (0-100)"),
        demographics_weight: float = Field(default=weights.demographics, description="Weight for demographics score (0-100)"),
        competition_weight: float = Field(default=weights.competition, description="Weight for competition score (0-100)"),
        healthcare_weight: float = Field(default=weights.healthcare, description="Weight for healthcare ecosystem score (0-100)"),
        complementary_weight: float = Field(default=weights.complementary, description="Weight for complementary businesses score (0-100)"),
        custom_locations_json: Optional[str] = Field(
            default=None,
            description='Optional JSON string of custom locations, e.g., \'[{"lat": 24.7136, "lng": 46.6753}]\'',
        ),
        current_location_json: Optional[str] = Field(
            default=None,
            description='Optional JSON string of current location, e.g., \'{"lat": 24.7136, "lng": 46.6753}\'',
        ),
    ) -> str:
        try:
            app_ctx = get_app_context(mcp)
            auth = await require_auth(app_ctx.session_manager)
            if isinstance(auth, str):
                return auth
            _session, user_id, id_token = auth

            logger.info("Generating pharmacy report for %s, %s", city_name, country_name)

            custom_locations = None
            if custom_locations_json:
                custom_locations = [
                    {"lat": loc["lat"], "lng": loc["lng"]}
                    for loc in json.loads(custom_locations_json)
                ]
            current_location = json.loads(current_location_json) if current_location_json else None

            request_body = {
                "user_id": user_id,
                "city_name": city_name,
                "country_name": country_name,
                "potential_business_type": defaults.potential_business_type,
                "ecosystem_string_name": defaults.ecosystem_string_name,
                "target_income_level": defaults.target_income_level,
                "target_age": defaults.target_age,
                "analysis_radius": defaults.analysis_radius,
                "complementary_categories": defaults.complementary_categories,
                "optimal_num_complementary_businesses_per_category": defaults.optimal_num_complementary_businesses_per_category,
                "cross_shopping_categories": defaults.cross_shopping_categories,
                "optimal_num_cross_shopping_businesses_per_category": defaults.optimal_num_cross_shopping_businesses_per_category,
                "competition_categories": defaults.competition_categories,
                "max_competition_threshold_per_category": defaults.max_competition_threshold_per_category,
                "evaluation_metrics": {
                    "traffic": traffic_weight / 100.0,
                    "demographics": demographics_weight / 100.0,
                    "competition": competition_weight / 100.0,
                    "complementary": (healthcare_weight + complementary_weight) / 200.0,
                    "cross_shopping": defaults.cross_shopping_weight,
                },
            }
            if custom_locations:
                request_body["custom_locations"] = custom_locations
            if current_location:
                request_body["current_location"] = current_location

            api_response = await call_backend(
                "smart_pharmacy_report",
                request_body,
                id_token,
                "Pharmacy site analysis via MCP tool",
            )

            if "error" in api_response:
                return json.dumps(
                    {
                        "report_file": "",
                        "data_files": {},
                        "response": f"❌ API Error: {api_response['error']}\nDetails: {api_response.get('details', 'No details')}",
                        "metadata": {"error": True, "analysis_type": "pharmacy_site_selection", "city": city_name},
                    },
                    ensure_ascii=False,
                    indent=2,
                )

            html_file_path = str(api_response.get("data", {}).get("html_file_path", ""))
            report_content = _build_markdown(city_name, html_file_path)
            full_report_path = await save_report(report_content, city_name, "pharmacy_report")

            return json.dumps(
                {
                    "report_file": full_report_path,
                    "data_files": {},
                    "response": (
                        f"✅ Pharmacy site analysis report generated for {city_name}, {country_name}.\n"
                        f"📄 Report: {full_report_path}\n"
                        f"📊 HTML Report: {html_file_path}"
                    ),
                    "metadata": {
                        "analysis_type": "pharmacy_site_selection",
                        "city": city_name,
                        "country": country_name,
                        "report_generated": True,
                        "html_file_path": html_file_path,
                        "evaluation_weights": {
                            "traffic": traffic_weight,
                            "demographics": demographics_weight,
                            "competition": competition_weight,
                            "healthcare": healthcare_weight,
                            "complementary": complementary_weight,
                        },
                    },
                },
                ensure_ascii=False,
                indent=2,
            )

        except Exception as e:
            logger.exception("Error serving pharmacy report")
            return json.dumps(
                {
                    "report_file": "",
                    "data_files": {},
                    "response": f"❌ Error: Failed to serve pharmacy report: {e}",
                    "metadata": {"error": True, "analysis_type": "pharmacy_site_selection", "city": city_name},
                },
                ensure_ascii=False,
                indent=2,
            )