import asyncio
import json
import os
from typing import Optional
from datetime import datetime
from mcp.server.fastmcp import FastMCP
from pydantic import Field, BaseModel

from context import get_app_context
from logging_config import get_logger
from config import config
from utils import post_to_backend, require_auth, BackendError

logger = get_logger(__name__)

# Report URL for browser-accessible links
REPORT_BASE_URL = "http://localhost:8000"


class EvaluationMetrics(BaseModel):
    """Evaluation metrics for pharmacy site scoring."""
    traffic: float = Field(default=25.0, description="Traffic score weight (default: 25.0)")
    demographics: float = Field(default=30.0, description="Demographics score weight (default: 30.0)")
    competition: float = Field(default=15.0, description="Competition score weight (default: 15.0)")
    healthcare: float = Field(default=20.0, description="Healthcare score weight (default: 20.0)")
    complementary: float = Field(default=10.0, description="Complementary businesses score weight (default: 10.0)")


def register_pharmacy_report_tools(mcp: FastMCP):
    """Register pharmacy report generation tool."""

    logger.info("Registering pharmacy report tool with MCP server")

    async def call_pharmacy_report_api(
        request_body: dict, jwt_token: str
    ) -> dict:
        """Call the pharmacy report API and return a normalized response dict."""
        try:
            data = await post_to_backend(
                config.endpoints.smart_pharmacy_report,
                request_body,
                jwt_token,
                "Pharmacy site analysis via MCP tool",
            )
            return {"data": data}
        except BackendError as e:
            logger.error("Pharmacy API error %s: %s", e.status, e.text)
            return {"error": f"API returned {e.status}", "details": e.text}
        except Exception as e:
            logger.error("Error calling pharmacy API: %s", e)
            return {"error": "Request failed", "details": str(e)}

    def generate_dynamic_markdown_report(city_name: str, html_file_path: str) -> str:
        """Generate markdown report with a dynamic link to the HTML report."""
        try:
            current_date = datetime.now().strftime("%B %d, %Y")

            if "reports" in html_file_path:
                parts = html_file_path.split("reports")
                if len(parts) > 1:
                    relative_path = parts[-1].replace("\\", "/").lstrip("/")
                    web_url = f"{REPORT_BASE_URL}/static/reports/{relative_path}"
                else:
                    web_url = html_file_path
            else:
                web_url = html_file_path

            return f"""# Pharmacy Site Analysis Report - {city_name}

Analysis completed for {city_name} on {current_date}.

[Click here to see full report]({web_url})

---
Generated by Geospatial Intelligence Platform
"""
        except Exception as e:
            logger.error("Error generating dynamic markdown report: %s", e)
            return f"# Pharmacy Report Error\n\nFailed to generate report: {e}"

    async def save_report_to_file(
        report_content: str, city_name: str, timestamp: str
    ) -> tuple[str, str]:
        """Save the markdown report to the reports directory."""
        try:
            reports_dir = config.reports_path
            os.makedirs(reports_dir, exist_ok=True)

            safe_city_name = "".join(
                c for c in city_name.replace(" ", "_") if c.isalnum() or c in "_-"
            )
            filename = f"{safe_city_name}_pharmacy_report_{timestamp}.md"
            file_path = os.path.join(reports_dir, filename)

            def _write():
                with open(file_path, "w", encoding="utf-8") as f:
                    f.write(report_content)

            await asyncio.to_thread(_write)

            logger.info("Report saved successfully: %s", filename)
            return filename, f"Report saved: {filename}"

        except Exception as e:
            logger.error("Error saving report: %s", e)
            return "", f"Error saving report: {e}"

    @mcp.tool(
        name="generate_pharmacy_report",
        description="""Generate comprehensive pharmacy site selection reports with real-time analysis.

        Analyzes locations based on multiple criteria including traffic, demographics, competition,
        healthcare ecosystem, and complementary businesses. Supports custom locations and evaluation metrics.

        Returns a detailed pharmacy site analysis report with rankings and investment recommendations.
        """,
    )
    async def generate_pharmacy_report(
        city_name: str = Field(default="Riyadh", description="Target city for pharmacy site analysis"),
        country_name: str = Field(default="Saudi Arabia", description="Target country"),
        traffic_weight: float = Field(default=25.0, description="Weight for traffic score (0-100)"),
        demographics_weight: float = Field(default=30.0, description="Weight for demographics score (0-100)"),
        competition_weight: float = Field(default=15.0, description="Weight for competition score (0-100)"),
        healthcare_weight: float = Field(default=20.0, description="Weight for healthcare ecosystem score (0-100)"),
        complementary_weight: float = Field(default=10.0, description="Weight for complementary businesses score (0-100)"),
        custom_locations_json: Optional[str] = Field(
            default=None,
            description='Optional JSON string of custom locations, e.g., \'[{"lat": 24.7136, "lng": 46.6753}]\'',
        ),
        current_location_json: Optional[str] = Field(
            default=None,
            description='Optional JSON string of current location, e.g., \'{"lat": 24.7136, "lng": 46.6753}\'',
        ),
    ) -> str:
        """Generate pharmacy site selection analysis using real-time API."""

        try:
            app_ctx = get_app_context(mcp)
            auth = await require_auth(app_ctx.session_manager)
            if isinstance(auth, str):
                return auth
            _session, user_id, id_token = auth

            logger.info("Generating pharmacy report for %s, %s", city_name, country_name)

            custom_locations = None
            if custom_locations_json:
                try:
                    custom_locations = [
                        {"lat": loc["lat"], "lng": loc["lng"]}
                        for loc in json.loads(custom_locations_json)
                    ]
                except Exception as e:
                    logger.error("Error parsing custom_locations_json: %s", e)

            current_location = None
            if current_location_json:
                try:
                    current_location = json.loads(current_location_json)
                except Exception as e:
                    logger.error("Error parsing current_location_json: %s", e)

            request_body = {
                "user_id": user_id,
                "city_name": city_name,
                "country_name": country_name,
                "potential_business_type": "pharmacy",
                "ecosystem_string_name": "healthcare",
                "target_income_level": "medium",
                "target_age": 30,
                "analysis_radius": 1000,
                "complementary_categories": ["hospital", "dentist"],
                "optimal_num_complementary_businesses_per_category": 2,
                "cross_shopping_categories": ["grocery_store", "supermarket"],
                "optimal_num_cross_shopping_businesses_per_category": 3,
                "competition_categories": ["pharmacy"],
                "max_competition_threshold_per_category": 1,
                "evaluation_metrics": {
                    "traffic": traffic_weight / 100.0,
                    "demographics": demographics_weight / 100.0,
                    "competition": competition_weight / 100.0,
                    "complementary": (healthcare_weight + complementary_weight) / 200.0,
                    "cross_shopping": 0.1,
                },
            }

            if custom_locations:
                request_body["custom_locations"] = custom_locations
            if current_location:
                request_body["current_location"] = current_location

            api_response = await call_pharmacy_report_api(request_body, id_token)

            if "error" in api_response:
                return json.dumps(
                    {
                        "report_file": "",
                        "data_files": {},
                        "response": f"❌ API Error: {api_response['error']}\nDetails: {api_response.get('details', 'No details')}",
                        "metadata": {"error": True, "analysis_type": "pharmacy_site_selection", "city": city_name},
                    },
                    ensure_ascii=False,
                    indent=2,
                )

            html_file_path = str(api_response.get("data", {}).get("html_file_path", ""))
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

            report_content = generate_dynamic_markdown_report(city_name, html_file_path)
            report_filename, save_message = await save_report_to_file(report_content, city_name, timestamp)

            if not report_filename:
                return json.dumps(
                    {
                        "report_file": "",
                        "data_files": {},
                        "response": f"❌ Error: {save_message}",
                        "metadata": {"error": True, "analysis_type": "pharmacy_site_selection", "city": city_name},
                    },
                    ensure_ascii=False,
                    indent=2,
                )

            reports_dir = config.reports_path
            full_report_path = os.path.join(reports_dir, report_filename)

            analysis_summary = (
                f"✅ Pharmacy site analysis report generated for {city_name}, {country_name}.\n"
                f"📄 Report: {report_filename}\n"
                f"🔗 {save_message}\n"
                f"📊 HTML Report: {html_file_path}"
            )

            return json.dumps(
                {
                    "report_file": str(full_report_path),
                    "data_files": {},
                    "response": analysis_summary,
                    "metadata": {
                        "analysis_type": "pharmacy_site_selection",
                        "city": city_name,
                        "country": country_name,
                        "report_generated": True,
                        "html_file_path": html_file_path,
                        "evaluation_weights": {
                            "traffic": traffic_weight,
                            "demographics": demographics_weight,
                            "competition": competition_weight,
                            "healthcare": healthcare_weight,
                            "complementary": complementary_weight,
                        },
                    },
                },
                ensure_ascii=False,
                indent=2,
            )

        except Exception as e:
            logger.exception("Error serving pharmacy report")
            return json.dumps(
                {
                    "report_file": "",
                    "data_files": {},
                    "response": f"❌ Error: Failed to serve pharmacy report: {e}",
                    "metadata": {"error": True, "analysis_type": "pharmacy_site_selection", "city": city_name},
                },
                ensure_ascii=False,
                indent=2,
            )