from mcp.server.fastmcp import FastMCP
from pydantic import Field
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import SystemMessage, HumanMessage

from config import config
from context import get_app_context
from logging_config import get_logger
from utils import get_secret, read_report_file

logger = get_logger(__name__)


def _build_llm(model: str, temperature: float) -> ChatGoogleGenerativeAI:
    return ChatGoogleGenerativeAI(
        model=model,
        temperature=temperature,
        google_api_key=get_secret("gemini_api_key"),
    )


def register_report_analysis_tools(mcp: FastMCP):
    @mcp.tool(
        name="report_analysis",
        description="""Analyze saved reports and answer questions using LLM.

        Analysis Capabilities:
        - Read and understand markdown report content
        - Answer specific questions about the report
        - Provide insights and explanations
        - Extract key findings and metrics

        Supported Report Types:
        - Territory optimization reports
        - Hub expansion analysis reports
        - Any markdown report generated by the system

        Usage:
        - Takes a report file handle/path and user question
        - Returns LLM-generated analysis and answers
        """,
    )
    async def report_analysis(
        report_file: str = Field(description="Path to the saved report file (markdown)"),
        user_query: str = Field(description="Question or analysis request about the report"),
        model: str = Field(default=config.llm.model, description="LLM model to use for analysis"),
        temperature: float = Field(default=config.llm.temperature, description="Temperature for LLM responses (0.0-1.0)"),
    ) -> str:
        try:
            app_ctx = get_app_context(mcp)
            user_id, id_token = await app_ctx.session_manager.get_valid_id_token()
            if not id_token or not user_id:
                return "❌ Error: You are not logged in. Please use the `user_login` tool first."

            report_content = read_report_file(report_file)
            if not report_content:
                return f"❌ Error: Could not read report file: {report_file}"

            logger.info("Analyzing report for user %s: %s", user_id, report_file)

            llm = _build_llm(model, temperature)
            system_prompt = (
                "You are an expert analyst reviewing a comprehensive report. "
                "Your task is to analyze the provided report content and answer the user's question with accuracy and insight.\n\n"
                "Report Analysis Guidelines:\n"
                "- Focus on the specific information requested in the user's query\n"
                "- Provide detailed, data-driven answers when possible\n"
                "- Reference specific sections, metrics, or findings from the report\n"
                "- If the report doesn't contain information needed to answer the query, clearly state this\n"
                "- Maintain a professional, analytical tone\n\n"
                f"Report Content:\n{report_content}\n"
            )

            response = llm.invoke([
                SystemMessage(content=system_prompt),
                HumanMessage(content=user_query),
            ])
            return response.content

        except Exception as e:
            logger.exception("Error in report_analysis")
            return f"❌ Error analyzing report: {e}"